### PR TITLE
Fix package tests

### PR DESCRIPTION
**Pull request by CermakM**
Package renamed: https://github.com/FusionAuth/fusionauth-jwt/commit/8a24e6b4cb0c8af3c32a560ebe867064e8152d3d

### CODE REVIEW

**Comment by CermakM** [comment]
Note: This does not fix `tests/test_feature_hooks.py:76: AssertionError`

**Review by tisnik — APPROVED** [review]
Looks good, I just write few comments ;)

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Pull request closed without merging**
